services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v1.1.1
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`homepage.home.neumanf.com`)
      - traefik.http.routers.homepage.entrypoints=web
      - traefik.http.services.homepage.loadbalancer.server.port=3000
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.home.neumanf.com
networks:
  traefik:
    external: true
